{% set version = "1.1.0" %}

package:
  name: bottleneck
  version: {{ version }}

source:
  fn: Bottleneck-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/B/Bottleneck/Bottleneck-{{ version }}.tar.gz
  sha256: c3a52b843509bd8d9ef240f0ce2f3e57d05277f85c3239196e3d8979fe5d33de

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - numpy x.x

  run:
    - python
    - numpy x.x

test:
  requires:
    - nose

  imports:
    - bottleneck
    - bottleneck.slow
    - bottleneck.tests
    - bottleneck.reduce
    - bottleneck.nonreduce
    - bottleneck.nonreduce_axis
    - bottleneck.move

  commands:
    - python -c "import bottleneck; bottleneck.test()"

about:
  home: http://berkeleyanalytics.com/bottleneck
  license: BSD 2-Clause
  license_family: BSD
  license_file: bottleneck/LICENSE
  summary: Fast NumPy array functions written in Cython.
  description: |
    Bottleneck is a collection of fast NumPy array functions written in
    Cython.
  doc_url: http://berkeleyanalytics.com/bottleneck
  dev_url: https://github.com/kwgoodman/bottleneck

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
