{% set version = "1.0.0" %}

package:
  name: bottleneck
  version: {{ version }}

source:
  fn: Bottleneck-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/B/Bottleneck/Bottleneck-{{ version }}.tar.gz
  sha256: 8d9b7ad4fadf9648acc924a6ee522c7cb5b474e75faaad9d90dfd55e2805b495

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - numpy x.x

  run:
    - python
    - numpy x.x

test:
  requires:
    - nose

  imports:
    - bottleneck
    - bottleneck.slow
    - bottleneck.tests
    - bottleneck.reduce
    - bottleneck.nonreduce
    - bottleneck.nonreduce_axis
    - bottleneck.move

  commands:
    - python -c "import bottleneck; bottleneck.test()"

about:
  home: http://berkeleyanalytics.com/bottleneck
  license: BSD 2-Clause
  license_family: BSD
  license_file: bottleneck/LICENSE
  summary: Fast NumPy array functions written in Cython.
  description: |
    Bottleneck is a collection of fast NumPy array functions written in
    Cython.
  doc_url: http://berkeleyanalytics.com/bottleneck
  dev_url: https://github.com/kwgoodman/bottleneck

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
