travis:
  secure:
    BINSTAR_TOKEN: 66CgRGAHMh06NEBCLXenNGhy59lHdkXfWDABnWsMY6TZ78+QuVxLyrkJmDl1TlOzNoud6J/mheOFp38Vgh0KW/DexheokfMl4bk3PoGdl1AqV4WECykDRwSe+FyVT82BevG6L5FbOwQc6rAGrvF5ogfnThzrVIl8nHrsW9oxSmMImeeo3LJNdDLAeLZdIYZLieoEFK9vGnObZJXWULwnHHSIvMhFyg0v8DdwnGIGzku5rkXFBzlUbTS53OPZHRLiAZnzTbgNIMi++luRyJQde4OAiYCZ5krm12SYvT562il/mckdjfBVTXdGbxG/zAxaKzfhOHals0Iw/y8razQf1MNKYDQgTgChTEds0q227Wy+7QXGzs55ciZRtp5T3205NYbw5jF2QqGAIomc/FylcSCX+xqkP3h+Lnv5/TKKYsgwGCdmOg7Ol3FtLQVJ2Q/sGIIfFh+yGmivcvjVc6qHSv1hDJUp1NmMFJi2J90caTcnn2fGJu4HUv7AkU4lLtTEsnX4sUGm7dc4GOKRyzIFTAEg7FUrx2D6xakM3k1bKbgdOM3cG6f+OyFtJavBPOMOtnRGBeCyVljIbQym21dCraj0b2evCEiLE8SFmYLz1g3q/86/f4hTw/93Yb350MEMKqabRVlEu8yzbL7/Tc6m/Bgw1utOttgBojkX3KzY3og=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
