travis:
  secure:
    BINSTAR_TOKEN: vp+1GHkMi4/R5gbJOi9HT40JKrYijCGm0dCe2T4+BeRRAwLZoBwCY3FmfKeR8kAmT9FEQnwCQu2WHc63b82u5wns80IyPrskvbuBZDeWuJm+pJ2VDSDJ6Aj7NXMbRia9+DUHfpkrgaCl8OG3Ik1KimU7DizPMofq/3/WPru0NSLgcRRpdPWOFIGhrQl0H/Tvkq6qyU+RT+gcyZDpR93hjcIwO2L/VHrAg5tHgYiDPaOlS3nCqw4qMhP03UuFYVUZY5EwJcNFn3WBVyRqOtcUtmmCR5BYYMalp/8FR5cHI4JURX9YdpfeZ7U33z43R+Yy9CuM/+HgOe783mA/XUQfBucOG/0vv0meNIgsOu8oODVHrqGc1wBPdjCPGESG0SBhaDAGiIRhcmZ3soGHeB5/ne7zti9U366kX1/KwbBssW9hY/5O5damAeqmAg+F8d1v0TdYLYf3PCjyuzk5GI66uQNfiOpH7D7BvuYQjOFhT3tFjVALl0fz2gTAj4ych0dmlYiXEPeZ4DrkmEj4kTAFpQKmzEoMJiHisgn0KyffYQpnG4kr6WsfhSoG4v9Rh7dF0FTDpuafkZlT7GC5GAdewWmJJ9jfTptyGjNa/OIaeu50XW6wgGP3ksq2aMvaHyDLxZr/Kmgoa//tnNcl92bvy4WQmW1spNULT/3t2caBm34=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
